spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=lucknow
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,info

logging.file.name=app.log
logging.file.path=D:\Demo Microservices\demo
logging.level.root=INFO
spring.jvm.args=-Dfile.encoding=UTF-8

